name: APPNAME_models
description: Shared models package for APPNAME
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  artifact: ^1.0.19
  crypto: ^3.0.7
  fire_crud: ^3.1.14
  toxic: ^1.3.8

dev_dependencies:
  artifact_gen: ^1.1.4
  build_runner: ^2.10.3
  fire_crud_gen: ^1.1.3
  lints: ^6.0.0

scripts:
  build_runner: flutter pub run build_runner build --delete-conflicting-outputs
  deploy_rules: cd .. && firebase use FIREBASE_PROJECT_ID && firebase deploy --only firestore && cd APPNAME
